### ISSUE TITLE
How to use `Git_jll` in my own package?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaBinaryWrappers/Git_jll.jl#1]
I have a number of Julia packages that use command-line git. Currently, this is an example of how my packages call command-line git:
```julia
run(`git push origin master`)
```

This of course requires the user to have `git` somewhere in their `PATH`.

I'd like to use `Git_jll` so that the user doesn't have to have `git` installed, but I have never used any BinaryBuilder packages before, so I have no idea where to start.

Presumably, if I can get the location of the `git` binary provided by `Git_jll` somehow, I can run that binary directly, i.e. if `LOCATION_OF_GIT_BINARY` is the location of the `git` binary provided by `Git_jll`, then I would run:
```julia
run(`$(LOCATION_OF_GIT_BINARY) push origin master`)
```

How can I get the location of the `git` binary provided by `Git_jll`?

cc: @staticfloat @giordano

**Comment by giordano** [comment]
Have you read the [README.md](https://github.com/JuliaBinaryWrappers/Git_jll.jl/blob/b12a1a01ba1a0130f8f33de8ea8ba02996ca75a9/README.md)?

**Comment by DilumAluthge** [comment]
```julia
# For executable products, you can use the exported variable name as a function that you can call
mungify_exe() do mungify_exe_path
    run(`$mungify_exe_path $num_chars`)
end
```

Presumably I need to figure out what the equivalent of `Git_jll.mungify_exe()` is? I'm assuming that `mungify_exe` is an example like `foo` or `bar`?

I grepped the repo for `exe` but couldn't find any functions under `Git_jll` with `exe` in the name.

**Comment by giordano** [comment]
As explained in the README.md, `mungify_exe` is the name of the executable product as declared in the builder.  In the [case of Git](https://github.com/JuliaPackaging/Yggdrasil/blob/8c1f2615465ae7aa09bc0f51f8a621e240a76b45/G/Git/build_tarballs.jl#L61-L63) the only executable product is called `git`, so
```julia
git() do git_path
    run(`$git_path push origin master`)
end
```

**Comment by DilumAluthge** [comment]
Ah, I should have looked in the `Yggdrasil` recipe for the name of the executable product!

**Comment by giordano** [comment]
Or also `Git_jll.` and then press `TAB` to have an idea of what's inside the package.

`Git_jll.git_path` is the absolute path to the executable, but generally speaking you need to setup some environment variables to make it work, that's why there is a wrapper function, which takes care of this under the hood.
